FROM python:3.10-slim

WORKDIR /app

COPY . .
         
RUN apt-get update && apt-get install -y strace curl --no-install-recommends && \
    pip install --no-cache-dir flask gunicorn && \
    rm -rf /var/lib/apt/lists/*

# Jalankan gunicorn lewat strace, simpan trace ke /tmp/strace.out-%p
CMD ["sh", "-c", "strace -ff -o /tmp/strace.out -s 200 -tt -f gunicorn --workers 4 --bind 0.0.0.0:5000 app:app"]

